# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thor/projects/sniffdogsniff

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thor/projects/sniffdogsniff

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thor/projects/sniffdogsniff/CMakeFiles /home/thor/projects/sniffdogsniff//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thor/projects/sniffdogsniff/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sniffdogsniffd

# Build rule for target.
sniffdogsniffd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sniffdogsniffd
.PHONY : sniffdogsniffd

# fast build rule for target.
sniffdogsniffd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/build
.PHONY : sniffdogsniffd/fast

kademlia/kadbucket.o: kademlia/kadbucket.cpp.o
.PHONY : kademlia/kadbucket.o

# target to build an object file
kademlia/kadbucket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/kademlia/kadbucket.cpp.o
.PHONY : kademlia/kadbucket.cpp.o

kademlia/kadbucket.i: kademlia/kadbucket.cpp.i
.PHONY : kademlia/kadbucket.i

# target to preprocess a source file
kademlia/kadbucket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/kademlia/kadbucket.cpp.i
.PHONY : kademlia/kadbucket.cpp.i

kademlia/kadbucket.s: kademlia/kadbucket.cpp.s
.PHONY : kademlia/kadbucket.s

# target to generate assembly for a file
kademlia/kadbucket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/kademlia/kadbucket.cpp.s
.PHONY : kademlia/kadbucket.cpp.s

kademlia/kadroutingtable.o: kademlia/kadroutingtable.cpp.o
.PHONY : kademlia/kadroutingtable.o

# target to build an object file
kademlia/kadroutingtable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/kademlia/kadroutingtable.cpp.o
.PHONY : kademlia/kadroutingtable.cpp.o

kademlia/kadroutingtable.i: kademlia/kadroutingtable.cpp.i
.PHONY : kademlia/kadroutingtable.i

# target to preprocess a source file
kademlia/kadroutingtable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/kademlia/kadroutingtable.cpp.i
.PHONY : kademlia/kadroutingtable.cpp.i

kademlia/kadroutingtable.s: kademlia/kadroutingtable.cpp.s
.PHONY : kademlia/kadroutingtable.s

# target to generate assembly for a file
kademlia/kadroutingtable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/kademlia/kadroutingtable.cpp.s
.PHONY : kademlia/kadroutingtable.cpp.s

localnode.o: localnode.cpp.o
.PHONY : localnode.o

# target to build an object file
localnode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/localnode.cpp.o
.PHONY : localnode.cpp.o

localnode.i: localnode.cpp.i
.PHONY : localnode.i

# target to preprocess a source file
localnode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/localnode.cpp.i
.PHONY : localnode.cpp.i

localnode.s: localnode.cpp.s
.PHONY : localnode.s

# target to generate assembly for a file
localnode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/localnode.cpp.s
.PHONY : localnode.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/main.cpp.s
.PHONY : main.cpp.s

msgpack11/msgpack11.o: msgpack11/msgpack11.cpp.o
.PHONY : msgpack11/msgpack11.o

# target to build an object file
msgpack11/msgpack11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/msgpack11/msgpack11.cpp.o
.PHONY : msgpack11/msgpack11.cpp.o

msgpack11/msgpack11.i: msgpack11/msgpack11.cpp.i
.PHONY : msgpack11/msgpack11.i

# target to preprocess a source file
msgpack11/msgpack11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/msgpack11/msgpack11.cpp.i
.PHONY : msgpack11/msgpack11.cpp.i

msgpack11/msgpack11.s: msgpack11/msgpack11.cpp.s
.PHONY : msgpack11/msgpack11.s

# target to generate assembly for a file
msgpack11/msgpack11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/msgpack11/msgpack11.cpp.s
.PHONY : msgpack11/msgpack11.cpp.s

net/libsam3.o: net/libsam3.c.o
.PHONY : net/libsam3.o

# target to build an object file
net/libsam3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/libsam3.c.o
.PHONY : net/libsam3.c.o

net/libsam3.i: net/libsam3.c.i
.PHONY : net/libsam3.i

# target to preprocess a source file
net/libsam3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/libsam3.c.i
.PHONY : net/libsam3.c.i

net/libsam3.s: net/libsam3.c.s
.PHONY : net/libsam3.s

# target to generate assembly for a file
net/libsam3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/libsam3.c.s
.PHONY : net/libsam3.c.s

net/netutil.o: net/netutil.c.o
.PHONY : net/netutil.o

# target to build an object file
net/netutil.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/netutil.c.o
.PHONY : net/netutil.c.o

net/netutil.i: net/netutil.c.i
.PHONY : net/netutil.i

# target to preprocess a source file
net/netutil.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/netutil.c.i
.PHONY : net/netutil.c.i

net/netutil.s: net/netutil.c.s
.PHONY : net/netutil.s

# target to generate assembly for a file
net/netutil.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/netutil.c.s
.PHONY : net/netutil.c.s

net/socks5.o: net/socks5.c.o
.PHONY : net/socks5.o

# target to build an object file
net/socks5.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/socks5.c.o
.PHONY : net/socks5.c.o

net/socks5.i: net/socks5.c.i
.PHONY : net/socks5.i

# target to preprocess a source file
net/socks5.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/socks5.c.i
.PHONY : net/socks5.c.i

net/socks5.s: net/socks5.c.s
.PHONY : net/socks5.s

# target to generate assembly for a file
net/socks5.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/socks5.c.s
.PHONY : net/socks5.c.s

net/tor.o: net/tor.c.o
.PHONY : net/tor.o

# target to build an object file
net/tor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/tor.c.o
.PHONY : net/tor.c.o

net/tor.i: net/tor.c.i
.PHONY : net/tor.i

# target to preprocess a source file
net/tor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/tor.c.i
.PHONY : net/tor.c.i

net/tor.s: net/tor.c.s
.PHONY : net/tor.s

# target to generate assembly for a file
net/tor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/net/tor.c.s
.PHONY : net/tor.c.s

rpc/sdsrpcclient.o: rpc/sdsrpcclient.cpp.o
.PHONY : rpc/sdsrpcclient.o

# target to build an object file
rpc/sdsrpcclient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/rpc/sdsrpcclient.cpp.o
.PHONY : rpc/sdsrpcclient.cpp.o

rpc/sdsrpcclient.i: rpc/sdsrpcclient.cpp.i
.PHONY : rpc/sdsrpcclient.i

# target to preprocess a source file
rpc/sdsrpcclient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/rpc/sdsrpcclient.cpp.i
.PHONY : rpc/sdsrpcclient.cpp.i

rpc/sdsrpcclient.s: rpc/sdsrpcclient.cpp.s
.PHONY : rpc/sdsrpcclient.s

# target to generate assembly for a file
rpc/sdsrpcclient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/rpc/sdsrpcclient.cpp.s
.PHONY : rpc/sdsrpcclient.cpp.s

rpc/sdsrpcserver.o: rpc/sdsrpcserver.cpp.o
.PHONY : rpc/sdsrpcserver.o

# target to build an object file
rpc/sdsrpcserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/rpc/sdsrpcserver.cpp.o
.PHONY : rpc/sdsrpcserver.cpp.o

rpc/sdsrpcserver.i: rpc/sdsrpcserver.cpp.i
.PHONY : rpc/sdsrpcserver.i

# target to preprocess a source file
rpc/sdsrpcserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/rpc/sdsrpcserver.cpp.i
.PHONY : rpc/sdsrpcserver.cpp.i

rpc/sdsrpcserver.s: rpc/sdsrpcserver.cpp.s
.PHONY : rpc/sdsrpcserver.s

# target to generate assembly for a file
rpc/sdsrpcserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/rpc/sdsrpcserver.cpp.s
.PHONY : rpc/sdsrpcserver.cpp.s

sds_config.o: sds_config.cpp.o
.PHONY : sds_config.o

# target to build an object file
sds_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/sds_config.cpp.o
.PHONY : sds_config.cpp.o

sds_config.i: sds_config.cpp.i
.PHONY : sds_config.i

# target to preprocess a source file
sds_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/sds_config.cpp.i
.PHONY : sds_config.cpp.i

sds_config.s: sds_config.cpp.s
.PHONY : sds_config.s

# target to generate assembly for a file
sds_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/sds_config.cpp.s
.PHONY : sds_config.cpp.s

sdstask.o: sdstask.cpp.o
.PHONY : sdstask.o

# target to build an object file
sdstask.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/sdstask.cpp.o
.PHONY : sdstask.cpp.o

sdstask.i: sdstask.cpp.i
.PHONY : sdstask.i

# target to preprocess a source file
sdstask.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/sdstask.cpp.i
.PHONY : sdstask.cpp.i

sdstask.s: sdstask.cpp.s
.PHONY : sdstask.s

# target to generate assembly for a file
sdstask.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/sdstask.cpp.s
.PHONY : sdstask.cpp.s

searchengine.o: searchengine.cpp.o
.PHONY : searchengine.o

# target to build an object file
searchengine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/searchengine.cpp.o
.PHONY : searchengine.cpp.o

searchengine.i: searchengine.cpp.i
.PHONY : searchengine.i

# target to preprocess a source file
searchengine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/searchengine.cpp.i
.PHONY : searchengine.cpp.i

searchengine.s: searchengine.cpp.s
.PHONY : searchengine.s

# target to generate assembly for a file
searchengine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/searchengine.cpp.s
.PHONY : searchengine.cpp.s

searchentriesdb.o: searchentriesdb.cpp.o
.PHONY : searchentriesdb.o

# target to build an object file
searchentriesdb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/searchentriesdb.cpp.o
.PHONY : searchentriesdb.cpp.o

searchentriesdb.i: searchentriesdb.cpp.i
.PHONY : searchentriesdb.i

# target to preprocess a source file
searchentriesdb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/searchentriesdb.cpp.i
.PHONY : searchentriesdb.cpp.i

searchentriesdb.s: searchentriesdb.cpp.s
.PHONY : searchentriesdb.s

# target to generate assembly for a file
searchentriesdb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/searchentriesdb.cpp.s
.PHONY : searchentriesdb.cpp.s

webserver/Jinja2CppLight.o: webserver/Jinja2CppLight.cpp.o
.PHONY : webserver/Jinja2CppLight.o

# target to build an object file
webserver/Jinja2CppLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/Jinja2CppLight.cpp.o
.PHONY : webserver/Jinja2CppLight.cpp.o

webserver/Jinja2CppLight.i: webserver/Jinja2CppLight.cpp.i
.PHONY : webserver/Jinja2CppLight.i

# target to preprocess a source file
webserver/Jinja2CppLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/Jinja2CppLight.cpp.i
.PHONY : webserver/Jinja2CppLight.cpp.i

webserver/Jinja2CppLight.s: webserver/Jinja2CppLight.cpp.s
.PHONY : webserver/Jinja2CppLight.s

# target to generate assembly for a file
webserver/Jinja2CppLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/Jinja2CppLight.cpp.s
.PHONY : webserver/Jinja2CppLight.cpp.s

webserver/httpserver.o: webserver/httpserver.cpp.o
.PHONY : webserver/httpserver.o

# target to build an object file
webserver/httpserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/httpserver.cpp.o
.PHONY : webserver/httpserver.cpp.o

webserver/httpserver.i: webserver/httpserver.cpp.i
.PHONY : webserver/httpserver.i

# target to preprocess a source file
webserver/httpserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/httpserver.cpp.i
.PHONY : webserver/httpserver.cpp.i

webserver/httpserver.s: webserver/httpserver.cpp.s
.PHONY : webserver/httpserver.s

# target to generate assembly for a file
webserver/httpserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/httpserver.cpp.s
.PHONY : webserver/httpserver.cpp.s

webserver/sdswebuiserver.o: webserver/sdswebuiserver.cpp.o
.PHONY : webserver/sdswebuiserver.o

# target to build an object file
webserver/sdswebuiserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/sdswebuiserver.cpp.o
.PHONY : webserver/sdswebuiserver.cpp.o

webserver/sdswebuiserver.i: webserver/sdswebuiserver.cpp.i
.PHONY : webserver/sdswebuiserver.i

# target to preprocess a source file
webserver/sdswebuiserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/sdswebuiserver.cpp.i
.PHONY : webserver/sdswebuiserver.cpp.i

webserver/sdswebuiserver.s: webserver/sdswebuiserver.cpp.s
.PHONY : webserver/sdswebuiserver.s

# target to generate assembly for a file
webserver/sdswebuiserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/sdswebuiserver.cpp.s
.PHONY : webserver/sdswebuiserver.cpp.s

webserver/stringhelper.o: webserver/stringhelper.cpp.o
.PHONY : webserver/stringhelper.o

# target to build an object file
webserver/stringhelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/stringhelper.cpp.o
.PHONY : webserver/stringhelper.cpp.o

webserver/stringhelper.i: webserver/stringhelper.cpp.i
.PHONY : webserver/stringhelper.i

# target to preprocess a source file
webserver/stringhelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/stringhelper.cpp.i
.PHONY : webserver/stringhelper.cpp.i

webserver/stringhelper.s: webserver/stringhelper.cpp.s
.PHONY : webserver/stringhelper.s

# target to generate assembly for a file
webserver/stringhelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sniffdogsniffd.dir/build.make CMakeFiles/sniffdogsniffd.dir/webserver/stringhelper.cpp.s
.PHONY : webserver/stringhelper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... sniffdogsniffd"
	@echo "... kademlia/kadbucket.o"
	@echo "... kademlia/kadbucket.i"
	@echo "... kademlia/kadbucket.s"
	@echo "... kademlia/kadroutingtable.o"
	@echo "... kademlia/kadroutingtable.i"
	@echo "... kademlia/kadroutingtable.s"
	@echo "... localnode.o"
	@echo "... localnode.i"
	@echo "... localnode.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... msgpack11/msgpack11.o"
	@echo "... msgpack11/msgpack11.i"
	@echo "... msgpack11/msgpack11.s"
	@echo "... net/libsam3.o"
	@echo "... net/libsam3.i"
	@echo "... net/libsam3.s"
	@echo "... net/netutil.o"
	@echo "... net/netutil.i"
	@echo "... net/netutil.s"
	@echo "... net/socks5.o"
	@echo "... net/socks5.i"
	@echo "... net/socks5.s"
	@echo "... net/tor.o"
	@echo "... net/tor.i"
	@echo "... net/tor.s"
	@echo "... rpc/sdsrpcclient.o"
	@echo "... rpc/sdsrpcclient.i"
	@echo "... rpc/sdsrpcclient.s"
	@echo "... rpc/sdsrpcserver.o"
	@echo "... rpc/sdsrpcserver.i"
	@echo "... rpc/sdsrpcserver.s"
	@echo "... sds_config.o"
	@echo "... sds_config.i"
	@echo "... sds_config.s"
	@echo "... sdstask.o"
	@echo "... sdstask.i"
	@echo "... sdstask.s"
	@echo "... searchengine.o"
	@echo "... searchengine.i"
	@echo "... searchengine.s"
	@echo "... searchentriesdb.o"
	@echo "... searchentriesdb.i"
	@echo "... searchentriesdb.s"
	@echo "... webserver/Jinja2CppLight.o"
	@echo "... webserver/Jinja2CppLight.i"
	@echo "... webserver/Jinja2CppLight.s"
	@echo "... webserver/httpserver.o"
	@echo "... webserver/httpserver.i"
	@echo "... webserver/httpserver.s"
	@echo "... webserver/sdswebuiserver.o"
	@echo "... webserver/sdswebuiserver.i"
	@echo "... webserver/sdswebuiserver.s"
	@echo "... webserver/stringhelper.o"
	@echo "... webserver/stringhelper.i"
	@echo "... webserver/stringhelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

